# Generated by Django 3.1.5 on 2021-01-12 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("park_required", models.BooleanField(db_index=True, default=False)),
                ("gym_required", models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutStyle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("is_public", models.BooleanField(db_index=True, default=False)),
                ("is_premium", models.BooleanField(db_index=True, default=False)),
                ("exercices", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "workout_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.workoutstyle",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="Exercice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("video", models.FileField(blank=True, null=True, upload_to="")),
                ("reps_duration", models.IntegerField(default=45)),
                ("is_duration", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "equipments",
                    models.ManyToManyField(blank=True, to="workouts.Equipment"),
                ),
                ("muscle_groups", models.ManyToManyField(to="workouts.MuscleGroup")),
            ],
            options={
                "ordering": ("-created_at",),
                "get_latest_by": "created_at",
            },
        ),
    ]
